name: Sync Discord messages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    name: Synchronize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: '0.5.4'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize
        run: bun scripts/sync.ts
        env:
          RESOURCES_WEBHOOK_URL: ${{ secrets.RESOURCES_WEBHOOK_URL }}
          RESOURCES_MESSAGE_ID: ${{ secrets.RESOURCES_MESSAGE_ID }}
